[meta]
NAME = "marketplace-solver"
DESCRIPTION = "Espresso Marketplace Solver"
FORMAT_VERSION = "0.1.0"

[route.submit_bid]
PATH = ["submit_bid"]
METHOD = "POST"
DOC = """
Submit a `BidTx` to the solver for a particular view
"""

[route.auction_results]
PATH = ["auction_results/:view_number"]
":view_number" = "Integer"
METHOD = "GET"
DOC = """
Fetch auction results for a particular view number.  This is the non-permissioned endpoint and will not return results that are not finalized yet. 
"""

[route.auction_results_permissioned]
PATH = ["auction_results_permissioned/:view_number/:signature"]
":view_number" = "Integer"
":signature" = "TaggedBase64"
METHOD = "GET"
DOC = """
Fetch auction results for a particular view number.  This is a permissioned endpoint.  Only the leader for the view will be able to access this endpoint.  This will return finalized auction results.  
"""

[route.register_rollup]
PATH = ["register_rollup"]
METHOD = "POST"
DOC = """
Registers a rollup using the `RollupRegistration` data in the body of the request.  Return an error if the requested namespace id is already taken. 
"""

[route.update_rollup]
PATH = ["update_rollup"]
METHOD = "POST"
DOC = """
Updates a rollup registration using the `RollupRegistration` data in the body of the request.  Returns an error if the request is not authenicated properly. 
"""

[route.rollup_registrations]
PATH = ["rollup_registrations"]
METHOD = "GET"
DOC = """
Returns all the currently registered rollups and their registration information
"""