name: update-flake-lock

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@V28

      - uses: cachix/cachix-action@v15
        with:
          name: espresso-systems-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v22
        with:
          pr-title: "Weekly PR to bump flake.nix" 
